#! /usr/bin/env python

import os
import stat

import subprocess
import shutil

import numpy as np

from pastis.algorithms import run_pm2


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description='Run PM2.')
    parser.add_argument('directory', metavar='N', type=str,
                        help='directory')
    args = parser.parse_args()
    run_pm2(args.directory)
